// prototype-nav.jsx — clickable prototype shell: screen registry, flow wiring, chrome.
// Reuses the exact screen components from the design canvas. Nothing is re-drawn here.

// ── flow registry ────────────────────────────────────────────────────────────
// mode: drives which tab bar targets are wired ("ride" | "drive" | null = no tabs)
// next: where the primary (accent) button goes
// links: [text fragment, target] — matched case-insensitively against control text
const FLOW = [
  { g: "Onboarding & sign-in", m: null, s: [
    { id: "S01", n: "Splash", el: <CgSplashScreen/>, next: "S02a" },
    { id: "S02a", n: "Onboarding · overlap", el: <CgOnboardingScreen step={0}/>, next: "S02b", links: [["skip", "S03"]] },
    { id: "S02b", n: "Onboarding · ride along", el: <CgOnboardingScreen step={1}/>, next: "S02c", links: [["skip", "S03"]] },
    { id: "S02c", n: "Onboarding · fill seats", el: <CgOnboardingScreen step={2}/>, next: "S02d", links: [["skip", "S03"]] },
    { id: "S02d", n: "Onboarding · safety", el: <CgOnboardingScreen step={3}/>, next: "S03" },
    { id: "S03", n: "Sign in", el: <CgLoginScreen/>, next: "S04" },
    { id: "S04", n: "Verify code", el: <CgOtpScreen/>, next: "S05" },
    { id: "S05", n: "Profile setup", el: <CgProfileSetupScreen/>, next: "S06" },
    { id: "S06", n: "Push priming", el: <CgPushPrimingScreen/>, next: "P01", links: [["not now", "P01"]] },
  ]},
  { g: "Passenger · find a ride", m: "ride", s: [
    { id: "P01", n: "Home · map", el: <PxHomeScreen/>, next: "P03", links: [["become a driver", "D01"], ["where to search", "P03"]] },
    { id: "P01b", n: "Home · resume trip", el: <PxHomeScreen resume/>, next: "P15", links: [["resume", "P15"], ["where to search", "P03"]] },
    { id: "P02", n: "Home · commuter board", el: <PxHomeDashScreen/>, next: "P04", links: [["matches", "P04"], ["become a driver", "D01"]] },
    { id: "P03", n: "Search", el: <PxSearchScreen/>, next: "P04" },
    { id: "P04", n: "Results · list", el: <PxResultsListScreen/>, next: "P07", links: [["map", "P06"]] },
    { id: "P05", n: "Results · grouped", el: <PxResultsGroupedScreen/>, next: "P07" },
    { id: "P06", n: "Results · map", el: <PxResultsMapScreen/>, next: "P07", links: [["list", "P04"]] },
    { id: "P07", n: "Ride detail", el: <PxRideDetailScreen/>, next: "P08", links: [["seat", "P08"], ["message driver", "P23"]] },
  ]},
  { g: "Passenger · book & pay", m: "ride", s: [
    { id: "P08", n: "Seat select", el: <PxSeatSelectScreen seatCount={1}/>, next: "P09", links: [["continue to pay", "P09"]] },
    { id: "P09", n: "Checkout · charged on start", el: <PxCheckoutScreen variant="approval"/>, next: "P11", links: [["add a card", "P10"]] },
    { id: "P09b", n: "Checkout · instant book", el: <PxCheckoutScreen variant="instant"/>, next: "P12", links: [["add a card", "P10"]] },
    { id: "P09c", n: "Checkout · trip already running", el: <PxCheckoutScreen variant="enroute"/>, next: "P12", links: [["add a card", "P10"]] },
    { id: "P09d", n: "Checkout · unpaid fee carried over", el: <PxCheckoutScreen variant="approval" dues/>, next: "P11", links: [["details", "P25"], ["add a card", "P10"]] },
    { id: "P09e", n: "Checkout · rewards credit applied", el: <PxCheckoutScreen variant="approval" credit/>, next: "P11", links: [["add a card", "P10"], ["reward", "P33"]] },
    { id: "P10", n: "Payment methods", el: <PxPaymentMethodsScreen/>, next: "P09", links: [["add a card", "P10"], ["visa", "P10"], ["mastercard", "P10"], ["cash", "P10"]] },
    { id: "P11", n: "Awaiting approval", el: <PxBookingStateScreen state="awaiting"/>, next: "P12", links: [["cancel", "P04"]] },
    { id: "P12", n: "Approved", el: <PxBookingStateScreen state="approved"/>, next: "P15", links: [["share", "P20"], ["chat", "P23"]] },
    { id: "P13", n: "Declined", el: <PxBookingStateScreen state="declined"/>, next: "P07", links: [["see all", "P04"]] },
    { id: "P22", n: "Driver cancelled · never charged", el: <PxBookingStateScreen state="cancelled"/>, next: "P03", links: [["find another seat", "P03"], ["contact support", "S25"], ["report", "S25"]] },
    { id: "P24", n: "Auto-cancelled · driver never started", el: <PxBookingStateScreen state="autocancelled"/>, next: "P03", links: [["book the next one", "P03"], ["contact support", "S25"]] },
    { id: "P14", n: "Seats just taken", el: <PxSeatsTakenScreen/>, next: "P04", links: [["instead", "P07"], ["see all", "P04"]] },
  ]},
  { g: "Passenger · during & after", m: "ride", s: [
    { id: "P15", n: "In trip", el: <PxInTripScreen/>, next: "P16", links: [["get off", "P16"], ["share trip", "P20"], ["emergency sos", "S27a"], ["chat with driver", "P23"]] },
    { id: "P16", n: "Get off early · request", el: <PxExitEarlyScreen state="request"/>, next: "P16c", links: [["stay on to", "P15"]] },
    { id: "P16b", n: "Get off early · 3rd, no adjustment", el: <PxExitEarlyScreen state="noadjust"/>, next: "P16c", links: [["stay on to", "P15"]] },
    { id: "P16c", n: "Get off early · driver pulling over", el: <PxExitEarlyScreen state="waiting"/>, next: "P17", links: [["message", "P23"], ["cancel the request", "P15"]] },
    { id: "P17", n: "Receipt", el: <PxReceiptScreen/>, next: "P18" },
    { id: "P17b", n: "Receipt · paid in cash", el: <PxReceiptScreen variant="cash"/>, next: "P18", links: [["outstanding amounts", "P25"]] },
    { id: "P17c", n: "Receipt · fare adjusted", el: <PxReceiptScreen variant="adjusted"/>, next: "P18", links: [["dispute", "S25"]] },
    { id: "P38", n: "Driver waiting · 5 min", el: <PxDriverWaitingScreen/>, next: "P38b", links: [["message", "P23"], ["chat with driver", "P23"]] },
    { id: "P38b", n: "Driver waiting · extended once", el: <PxDriverWaitingScreen extended/>, next: "P27", links: [["message", "P23"], ["chat with driver", "P23"]] },
    { id: "P39", n: "Your rating & reliability", el: <PxRiderRatingScreen/>, links: [["outstanding", "P25"]] },
    { id: "P18", n: "Rate driver", el: <PxRateDriverScreen/>, next: "P01" },
    { id: "P19", n: "Saved places", el: <PxSavedPlacesScreen/>, next: "P03", links: [["add a place", "P19"], ["home", "P03"], ["work", "P03"], ["amma", "P03"], ["gym", "P03"]] },
    { id: "P20", n: "Share trip", el: <PxShareTripScreen/>, next: "P21", links: [["revoke", "P20"], ["copy", "P20"]] },
    { id: "P21", n: "Public link · no app", el: <PxPublicTripScreen/> },
    { id: "P23", n: "Booking chat · passenger", el: <ChatScreen mode="ride"/>, links: [["view profile", "P07"], ["call", "P23"]] },
    { id: "P25", n: "Outstanding amounts · owed", el: <PxDuesScreen/>, next: "P25b", links: [["dispute", "S25"]] },
    { id: "P25b", n: "Outstanding amounts · clear", el: <PxDuesScreen settled/> },
    { id: "P26", n: "Cancelled after start · 20% kept", el: <PxPenaltyScreen kind="cancel"/>, next: "P03", links: [["dispute", "S25"], ["contact support", "S25"]] },
    { id: "P27", n: "No-show · 25% kept", el: <PxPenaltyScreen kind="noshow"/>, next: "P03", links: [["dispute", "S25"], ["contact support", "S25"]] },
  ]},
  { g: "Shared · account & history", m: "ride", s: [
    { id: "S15", n: "Account · dual role", el: <AccountScreen driver mode="ride"/>, links: [["your trips", "S17a"], ["trusted contact", "S28"], ["setting", "S18"], ["verif", "S19"], ["payment", "P10"], ["saved place", "P19"], ["help & support", "S24"], ["notification", "S23"], ["outstanding", "P25"], ["vehicle", "D06"], ["rating", "D28"], ["recurring", "D10"], ["earnings", "D25"], ["driving preferences", "D35"], ["your per-km rate", "D39"], ["verif", "P28"], ["invite", "P32"], ["reward", "D38"]] },
    { id: "S16", n: "Account · rider only", el: <AccountScreen driver={false}/>, links: [["your trips", "S17a"], ["trusted contact", "S28"], ["become a driver", "D01"], ["setting", "S18"], ["verif", "S19"], ["payment", "P10"], ["saved place", "P19"], ["outstanding", "P25"], ["help & support", "S24"], ["notification", "S23"], ["invite", "P32"], ["reward", "P33"], ["your rating", "P39"]] },
    { id: "S17a", n: "Trip history · rides", el: <TripHistoryScreen tab="Rides"/>, next: "P17", links: [["drives", "S17b"]] },
    { id: "S17b", n: "Trip history · drives", el: <TripHistoryScreen tab="Drives"/>, next: "D24", links: [["rides", "S17a"]] },
    { id: "S18", n: "Settings", el: <SettingsScreen/>, links: [["theme", "S18"], ["language", "S18"], ["payment method", "P10"], ["receipts by email", "S23"], ["download my data", "S18"], ["terms", "S18"], ["community rules", "S18"], ["rate comigo", "S18"], ["delete my account", "S13"], ["share live location", "P20"], ["show my rating", "D28"]] },
  ]},
  { g: "Shared · inbox & prefs", m: "ride", s: [
    { id: "S22", n: "Inbox + broadcast", el: <InboxScreen/>, links: [["heavy rain", "S22"], ["approved your seat", "P12"], ["new booking", "D16"], ["payout sent", "D27"], ["how was your trip", "P18"], ["insurance expires", "S19"], ["mark all read", "S22"], ["all", "S22"], ["trips", "S22"], ["money", "S22"], ["account", "S22"], ["notification preferences", "S23"]] },
    { id: "S22b", n: "Inbox · push off", el: <InboxScreen notifsOff/>, next: "S23", links: [["open settings", "S23"], ["heavy rain", "S22"], ["approved your seat", "P12"], ["new booking", "D16"], ["payout sent", "D27"], ["how was your trip", "P18"], ["insurance expires", "S19"], ["notification preferences", "S23"]] },
    { id: "S23", n: "Notification preferences", el: <NotifPrefsScreen/> },
  ]},
  { g: "Shared · verification", m: "ride", s: [
    { id: "S19", n: "Verification status", el: <VerificationScreen/>, next: "S20", links: [["renew", "S20"], ["redo", "S20"], ["add", "S20"]] },
    { id: "S20", n: "Document upload", el: <DocUploadScreen/>, next: "S21a" },
    { id: "S21a", n: "Outcome · pending", el: <DocOutcomeScreen outcome="pending"/>, next: "S19" },
    { id: "S21b", n: "Outcome · approved", el: <DocOutcomeScreen outcome="approved"/>, next: "S19" },
    { id: "S21c", n: "Outcome · rejected", el: <DocOutcomeScreen outcome="rejected"/>, next: "S20", links: [["retake photo", "S20"], ["talk to support", "S25"]] },
  ]},
  { g: "Shared · support & safety", m: "ride", s: [
    { id: "S24", n: "Help centre", el: <HelpCenterScreen/>, next: "S25", links: [["route matching", "S24"], ["fares, refunds", "P17"], ["cancellations", "D21"], ["payment problems", "P10"], ["verification and documents", "S19"], ["payouts and commission", "D27"], ["managing passengers", "D20"], ["message support", "S25"], ["call comigo", "S24"], ["emergency", "S27a"], ["open ticket", "S26"]] },
    { id: "S25", n: "Support tickets", el: <TicketListScreen/>, next: "S26", links: [["charged twice", "S26"], ["longer route", "S26"], ["licence rejected", "S26"], ["payout not received", "S26"], ["new ticket", "S26"]] },
    { id: "S26", n: "Ticket thread", el: <TicketThreadScreen/> },
    { id: "S27a", n: "SOS · riding", el: <SosScreen mode="ride"/>, next: "P15", links: [["close", "P15"], ["call 119", "S27a"], ["safety team", "S25"], ["alert my trusted contacts", "P20"]] },
    { id: "S27b", n: "SOS · driving", el: <SosScreen mode="drive"/>, next: "D18", links: [["close", "D18"], ["call 119", "S27b"], ["safety team", "S25"], ["alert my trusted contacts", "P20"]] },
    { id: "S28", n: "Safety centre", el: <SafetyCenterScreen/>, next: "S27a", links: [["share my live trip", "P20"], ["report a problem", "S25"], ["hide my number", "S28"], ["emergency", "S27a"]] },
  ]},
  { g: "Mode switching & gates", m: "ride", s: [
    { id: "S07", n: "Passenger only · no chip", el: <ModeStateNoneScreen/>, next: "D01", links: [["become a driver", "D01"]] },
    { id: "S08", n: "Driver PENDING · gated", el: <ModeStatePendingScreen/>, next: "S19", links: [["keep riding", "P01"], ["see my application", "S19"]] },
    { id: "S09", n: "Driver REJECTED · gated", el: <ModeStateRejectedScreen/>, next: "S20", links: [["re-upload licence", "S20"], ["talk to support", "S25"]] },
    { id: "S10", n: "Conflict · switch while riding", el: <ConflictActiveTripScreen/>, next: "D08", links: [["stay in this trip", "P15"]] },
    { id: "S11", n: "Conflict · booking while driving", el: <ConflictDrivingNotifScreen/>, next: "D18", links: [["later", "D18"], ["drop off", "D22"]] },
    { id: "S12", n: "Conflict · publish before KYC", el: <ConflictPublishGateScreen/>, next: "D02", links: [["redo revenue licence", "S20"], ["renew", "S20"], ["add", "S20"], ["back to riding", "P01"]] },
    { id: "S13", n: "Account suspended", el: <SuspendedScreen/>, next: "S25", links: [["support", "S25"]] },
  ]},
  { g: "Passenger · identity & verification", m: "ride", s: [
    { id: "P28", n: "Verify · why bother", el: <PxVerifyIntroScreen/>, next: "P29a", links: [["open the camera", "P29a"], ["not now", "P01"]] },
    { id: "P29a", n: "Capture · NIC front", el: <PxVerifyCaptureScreen step={1}/>, next: "P29b" },
    { id: "P29b", n: "Capture · NIC back", el: <PxVerifyCaptureScreen step={2}/>, next: "P29c" },
    { id: "P29c", n: "Capture · selfie with NIC", el: <PxVerifyCaptureScreen step={3}/>, next: "P30" },
    { id: "P29d", n: "Capture · profile selfie", el: <PxVerifyCaptureScreen step={4}/>, next: "P30" },
    { id: "P30", n: "Profile photo · matched only", el: <PxProfilePhotoScreen choice="MATCHED"/>, next: "P31a", links: [["submit", "P31a"], ["photo PUBLIC", "P30b"], ["photo HIDDEN", "P30c"]] },
    { id: "P30b", n: "Profile photo · public", el: <PxProfilePhotoScreen choice="PUBLIC"/>, next: "P31a", links: [["submit", "P31a"]] },
    { id: "P30c", n: "Profile photo · hidden", el: <PxProfilePhotoScreen choice="HIDDEN"/>, next: "P31a", links: [["submit", "P31a"]] },
    { id: "P31a", n: "Verification · in review", el: <PxVerifyStatusScreen state="pending"/>, next: "P31b", links: [["keep looking", "P01"], ["profile photo settings", "P30"]] },
    { id: "P31b", n: "Verification · verified", el: <PxVerifyStatusScreen state="verified"/>, next: "P04", links: [["verified-only trips", "P04"], ["profile photo settings", "P30"]] },
    { id: "P31c", n: "Verification · needs redoing", el: <PxVerifyStatusScreen state="rejected"/>, next: "P29b", links: [["retake", "P29b"]] },
  ]},
  { g: "Shared · referral & rewards", m: "ride", s: [
    { id: "P32", n: "Referral · rider view", el: <PxReferralScreen mode="ride"/>, next: "P33", links: [["rewards balance", "P33"], ["share my link", "P32"]] },
    { id: "D37", n: "Referral · driver view", el: <PxReferralScreen mode="drive"/>, next: "D38", links: [["rewards balance", "D38"], ["share my link", "D37"]] },
    { id: "P33", n: "Rewards · ride credit", el: <PxRewardsScreen mode="ride"/>, next: "P32", links: [["invite more", "P32"], ["use it on my next ride", "P09e"]] },
    { id: "D38", n: "Rewards · withdraw to bank", el: <PxRewardsScreen mode="drive"/>, next: "D37", links: [["invite more", "D37"]] },
    { id: "D38b", n: "Rewards · under the bank floor", el: <PxRewardsScreen mode="drive" held/>, next: "D37", links: [["invite more", "D37"]] },
  ]},
  { g: "Passenger · joining a moving trip", m: "ride", s: [
    { id: "P36", n: "Riding now · joinable trips", el: <PxLiveResultsScreen/>, next: "P37", links: [["ask ranjith", "P37"], ["ask tharindu", "P37"], ["scheduled", "P04"]] },
    { id: "P36b", n: "Riding now · all passed you", el: <PxLiveResultsScreen empty/>, next: "P04", links: [["scheduled trips instead", "P04"]] },
    { id: "P37", n: "Live request · waiting", el: <PxLiveRequestScreen state="waiting"/>, next: "P37b", links: [["withdraw", "P36"]] },
    { id: "P37b", n: "Live request · accepted & charged", el: <PxLiveRequestScreen state="accepted"/>, next: "P15", links: [["track his car", "P15"]] },
    { id: "P37c", n: "Live request · he never answered", el: <PxLiveRequestScreen state="lapsed"/>, next: "P36", links: [["ask tharindu", "P37"]] },
  ]},
  { g: "Passenger · when the driver is late", m: "ride", s: [
    { id: "P34", n: "Driver late · free cancel", el: <PxBookingStateScreen state="driverlate"/>, next: "P22", links: [["keep waiting", "P12"], ["cancel", "P22"]] },
    { id: "P35", n: "Driver hasn't started", el: <PxBookingStateScreen state="notstarted"/>, next: "P24", links: [["give him", "P12"], ["cancel", "P24"]] },
  ]},
  { g: "Driver · becoming one", m: "drive", s: [
    { id: "D01", n: "Become a driver", el: <DvBecomeScreen/>, next: "D02" },
    { id: "D02", n: "KYC · identity", el: <DvKycScreen step={1}/>, next: "D03" },
    { id: "D03", n: "KYC · licence", el: <DvKycScreen step={2}/>, next: "D04" },
    { id: "D04", n: "KYC · vehicle", el: <DvKycScreen step={3}/>, next: "D05" },
    { id: "D05", n: "Application pending", el: <DvKycPendingScreen/>, next: "D08", links: [["back to riding", "P01"], ["message support", "S25"]] },
    { id: "D06", n: "Vehicles", el: <DvVehiclesScreen/>, next: "D07", links: [["add", "D07"]] },
    { id: "D07", n: "Add vehicle", el: <DvAddVehicleScreen/>, next: "D06" },
  ]},
  { g: "Driver · publishing trips", m: "drive", s: [
    { id: "D08", n: "Dashboard · earnings", el: <DvHomeScreen/>, next: "D11", links: [["request", "D16"], ["recurring", "D10"], ["renew", "S19"]] },
    { id: "D08b", n: "Dashboard · trip running", el: <DvHomeScreen live/>, next: "D18", links: [["resume the trip", "D18"], ["request", "D16"], ["recurring", "D10"], ["renew", "S19"]] },
    { id: "D09", n: "My trips", el: <DvTripListScreen/>, next: "D15", links: [["publish", "D11"], ["review", "D16"], ["edit", "D13b"], ["recurring", "D10"]] },
    { id: "D10", n: "Recurring routes", el: <DvRecurringScreen/>, next: "D09", links: [["generate", "D09"], ["pause", "D10"], ["cancel route", "D30"]] },
    { id: "D11", n: "Create · route", el: <DvCreateRouteScreen/>, next: "D12" },
    { id: "D12", n: "Create · schedule", el: <DvCreateScheduleScreen/>, next: "D13" },
    { id: "D13", n: "Create · seats & price", el: <DvCreatePriceScreen/>, next: "D14", links: [["publish", "D14"]] },
    { id: "D13b", n: "Create · one form", el: <DvCreateFormScreen/>, next: "D14", links: [["publish", "D14"]] },
    { id: "D14", n: "Published + QR", el: <DvPublishedScreen/>, next: "D15", links: [["share", "D14"], ["view the trip", "D15"]] },
    { id: "D15", n: "Trip detail", el: <DvTripDetailScreen/>, next: "D17", links: [["seat request", "D16"], ["cancel trip", "D30"], ["chat with", "D36"]] },
    { id: "D16", n: "Booking requests · scheduled", el: <DvRequestsScreen/>, next: "D17", links: [["decline", "D16"]] },
    { id: "D16b", n: "Booking request · mid-trip", el: <DvRequestsScreen enRoute/>, next: "D18", links: [["decline", "D18"]] },
    { id: "D16c", n: "Live request · at the wheel", el: <DvLiveRequestScreen/>, next: "D18", links: [["accept", "D18"], ["decline", "D18"], ["mute", "D18"]] },
    { id: "D16d", n: "Live request · lapsed, pickup passed", el: <DvLiveRequestLapsedScreen/>, next: "D18", links: [["back to the trip", "D18"], ["live request settings", "D35"]] },
    { id: "D16e", n: "Request lapsed · seat already sold", el: <DvRequestLapsedScreen/>, next: "D15", links: [["back to the trip", "D15"], ["preferences", "D35"], ["driving preferences", "D35"]] },
    { id: "D30", n: "Cancel trip · inside 12 h", el: <DvCancelTripScreen window="late"/>, next: "D31", links: [["keep the trip", "D15"]] },
    { id: "D30b", n: "Cancel trip · free window", el: <DvCancelTripScreen window="early"/>, next: "D31b", links: [["keep the trip", "D15"]] },
    { id: "D31", n: "Cancelled · penalty", el: <DvTripCancelledScreen window="late"/>, next: "D09", links: [["my rating", "D28"], ["manage route", "D10"], ["back to my trips", "D09"]] },
    { id: "D31b", n: "Cancelled · no penalty", el: <DvTripCancelledScreen window="early"/>, next: "D09", links: [["manage route", "D10"], ["back to my trips", "D09"]] },
    { id: "D32", n: "Start buffer · counting down", el: <DvStartBufferScreen state="counting"/>, next: "D18", links: [["cancel the trip instead", "D30"], ["chat with", "D36"], ["more minutes", "D32c"]] },
    { id: "D32c", n: "Start buffer · extension used", el: <DvStartBufferScreen state="extended"/>, next: "D18", links: [["cancel the trip instead", "D30"], ["chat with", "D36"]] },
    { id: "D32b", n: "Auto-cancelled · missed start", el: <DvStartBufferScreen state="autocancelled"/>, next: "D28", links: [["back to my trips", "D09"]] },
    { id: "D35", n: "Driving preferences", el: <DvPreferencesScreen/>, links: [["pref anyone", "D35"], ["pref women only", "D35"], ["verified riders only", "D35"], ["your per-km rate", "D39"]] },
    { id: "D39", n: "Per-km rate · your band", el: <DvRateBandScreen/>, next: "D13", links: [["all my vehicles", "D06"], ["request review", "S25"], ["rate min", "D39b"], ["rate max", "D39c"]] },
    { id: "D39b", n: "Per-km rate · bottom of band", el: <DvRateBandScreen picked="min"/>, next: "D13", links: [["all my vehicles", "D06"], ["rate mid", "D39"], ["rate max", "D39c"]] },
    { id: "D39c", n: "Per-km rate · top of band", el: <DvRateBandScreen picked="max"/>, next: "D13", links: [["all my vehicles", "D06"], ["rate mid", "D39"], ["rate min", "D39b"]] },
    { id: "D40", n: "Rate band · being set", el: <DvRatePendingScreen/>, next: "D06", links: [["switch car", "D11"], ["message support", "S25"], ["notify me", "D06"]] },
  ]},
  { g: "Driver · running the trip", m: "drive", s: [
    { id: "D17", n: "Pre-trip checklist", el: <DvChecklistScreen/>, next: "D18", links: [["start the trip", "D18"]] },
    { id: "D18", n: "Live trip · map", el: <DvLiveTripScreen/>, next: "D22", links: [["list view", "D18b"], ["emergency sos", "S27b"]] },
    { id: "D18b", n: "Live trip · list", el: <DvLiveListScreen/>, next: "D22", links: [["emergency sos", "S27b"], ["drop sanduni", "D22"]] },
    { id: "D18c", n: "Live trip · early drop request", el: <DvLiveTripScreen earlyRequest/>, next: "D22b", links: [["chat with", "D36"], ["next safe spot", "D18c"]] },
    { id: "D19", n: "Waiting at pickup · 5 min", el: <DvArrivedScreen/>, next: "D20", links: [["+5 min", "D19b"], ["chat with", "D36"]] },
    { id: "D19b", n: "Waiting at pickup · extended", el: <DvArrivedScreen extended/>, next: "D20", links: [["release his seat", "D21"], ["chat with", "D36"]] },
    { id: "D20", n: "Boarding", el: <DvBoardingScreen/>, next: "D22", links: [["release seat", "D21"]] },
    { id: "D21", n: "Release a no-show's seat", el: <DvNoShowScreen/>, next: "D18", links: [["keep waiting", "D19b"]] },
    { id: "D41", n: "You were late · rider cancelled free", el: <DvLatePenaltyScreen/>, next: "D18", links: [["my reliability", "D28"], ["dispute", "S25"]] },
    { id: "D22", n: "Drop off · as booked", el: <DvDropOffScreen kind="planned"/>, next: "D23", links: [["early drop", "D22b"], ["not yet", "D18"]] },
    { id: "D22b", n: "Drop off · early, fare adjusted", el: <DvDropOffScreen kind="early"/>, next: "D24", links: [["she stayed on", "D18"]] },
    { id: "D23", n: "Cash collected", el: <DvCashScreen/>, next: "D24" },
    { id: "D24", n: "Trip complete · rate each other", el: <DvTripCompleteScreen/>, next: "D25" },
    { id: "D36", n: "Booking chat · driver", el: <ChatScreen mode="drive"/>, links: [["view profile", "D15"], ["call", "D36"]] },
  ]},
  { g: "Driver · money", m: "drive", s: [
    { id: "D25", n: "Earnings", el: <DvEarningsScreen/>, next: "D26", links: [["transaction ledger", "D26"], ["weekly payout", "D33"], ["payout account", "D27"], ["fare adjustment", "D29"], ["wallet card", "D33"]] },
    { id: "D26", n: "Ledger", el: <DvLedgerScreen/>, next: "D29", links: [["payout to boc", "D27"]] },
    { id: "D27", n: "Payout account", el: <DvPayoutScreen/>, next: "D25" },
    { id: "D28", n: "Ratings & reliability", el: <DvRatingsScreen/>, next: "D08", links: [["what happens", "D34"]] },
    { id: "D29", n: "Fare adjustment · request", el: <DvFareAdjustScreen state="request"/>, next: "D29a" },
    { id: "D29a", n: "Adjustment · pending", el: <DvFareAdjustScreen state="pending"/>, next: "D29b" },
    { id: "D29b", n: "Adjustment · approved", el: <DvFareAdjustScreen state="approved"/>, next: "D26" },
    { id: "D29c", n: "Adjustment · rejected", el: <DvFareAdjustScreen state="rejected"/>, next: "D29", links: [["reply with more detail", "S26"], ["accept the decision", "D26"]] },
    { id: "D33", n: "Weekly payout · eligible", el: <DvMonthlyPayoutScreen state="eligible"/>, links: [["payout account", "D27"], ["last payout", "D26"], ["ledger", "D26"]] },
    { id: "D33b", n: "Weekly payout · held", el: <DvMonthlyPayoutScreen state="held"/>, links: [["payout account", "D27"], ["last payout", "D26"], ["ledger", "D26"], ["publish", "D11"]] },
    { id: "D34", n: "Driver deactivated · reapply", el: <DvDeactivatedScreen/>, next: "S25", links: [["keep riding as a passenger", "P01"]] },
  ]},
];

// Reference boards — specs, not app screens. Shown full-width, not in the phone.
const BOARDS = [
  { id: "B01", n: "Brand · three concepts", el: <BrandConceptsBoard/>, w: 1300 },
  { id: "B02", n: "Brand · construction", el: <BrandConstructionBoard/>, w: 1300 },
  { id: "B03", n: "Brand · scale & theme", el: <BrandScaleBoard/>, w: 1300 },
  { id: "B04", n: "Brand · ship assets", el: <BrandAssetsBoard/>, w: 1300 },
  { id: "B05", n: "Brand · wordmark type", el: <BrandTypeBoard/>, w: 1300 },
  { id: "S14", n: "Tab bars & badges", el: <TabBarSpecBoard/>, w: 1300 },
  { id: "X01", n: "Reusable state set", el: <StateSetBoard/>, w: 1300 },
  { id: "X02", n: "Feature-gated & degraded", el: <DegradedBoard/>, w: 1300 },
  { id: "V00", n: "Decisions & cut screens", el: <DecisionsBoard/>, w: 1300 },
];

const SCREENS = FLOW.flatMap(sec => sec.s.map(s => ({ ...s, group: sec.g, mode: s.mode ?? sec.m })));
const BY_ID = Object.fromEntries(SCREENS.map(s => [s.id, s]));
const BOARD_BY_ID = Object.fromEntries(BOARDS.map(b => [b.id, b]));
const TAB_TARGET = {
  ride: { home: "P01", trips: "S17a", action: "P03", inbox: "S22", account: "S15" },
  drive: { home: "D08", trips: "D09", action: "D11", inbox: "S22", account: "S15" },
};

Object.assign(window, { FLOW, BOARDS, SCREENS, BY_ID, BOARD_BY_ID, TAB_TARGET });
