import { HttpError, type ApiClient } from './api-client';
import { adaptBooking, adaptPassengerProfile, adaptPaymentIntent, adaptPlaceSuggestion, adaptRideSearchResult, adaptSavedPlace, adaptTrustedContact } from './adapters';
import type { Booking, PassengerProfile, PaymentIntent, PlaceSuggestion, RideSearchResult, SavedPlace, TrustedContact } from './types';

const mapList = <T>(items: unknown, adapter: (item: unknown) => T): T[] => Array.isArray(items) ? items.map(adapter) : [];

export const appConfigApi = (client: ApiClient) => ({ getConfig: () => client.request('/api/v1/app/config', { auth: false }) });
export const authApi = (client: ApiClient) => ({
  me: () => client.request('/api/v1/auth/me'),
  requestOtp: (body: { phoneNumber: string }) => client.request<{ verificationId: string; phoneNumber: string; expiresInSeconds: number; resendAfterSeconds: number }>('/api/v1/auth/otp/request', { method: 'POST', body, auth: false, retry: { attempts: 2 } }),
  verifyOtp: (body: { verificationId: string; phoneNumber: string; code: string }) => client.request<{ verified: boolean; phoneNumber: string; accessToken: string; expiresInSeconds: number }>('/api/v1/auth/otp/verify', { method: 'POST', body, auth: false }),
});
export const profileApi = (client: ApiClient) => ({
  get: async (): Promise<PassengerProfile> => {
    try { return adaptPassengerProfile(await client.request('/api/v1/passenger/profile')); }
    catch (error) {
      if (error instanceof HttpError && error.status === 404) return adaptPassengerProfile({ id: 'new', verificationStatus: 'readiness_only' });
      throw error;
    }
  },
  update: async (body: unknown): Promise<PassengerProfile> => adaptPassengerProfile(await client.request('/api/v1/passenger/profile', { method: 'PUT', body })),
  createAvatarUpload: (body: unknown) => client.request('/api/v1/passenger/profile/avatar-upload', { method: 'POST', body }),
  getVerificationStatus: async () => ({ status: (await client.request<PassengerProfile>('/api/v1/passenger/profile')).verificationStatus ?? 'readiness_only' }),
  uploadVerificationDocument: async (body: unknown) => ({ accepted: false, mode: 'readiness_only', body })
});
export const placesApi = (client: ApiClient) => ({
  autocomplete: async ({ query, latitude, longitude }: { query: string; latitude?: number; longitude?: number }): Promise<PlaceSuggestion[]> => mapList(await client.request('/api/v1/passenger/places/autocomplete', { query: { query, latitude, longitude } }), adaptPlaceSuggestion),
  details: async (placeId: string): Promise<PlaceSuggestion> => adaptPlaceSuggestion(await client.request('/api/v1/passenger/places/{placeId}', { pathParams: { placeId } })),
});
export const savedPlacesApi = (client: ApiClient) => ({ list: async (): Promise<SavedPlace[]> => mapList(await client.request('/api/v1/passenger/saved-places'), adaptSavedPlace), get: async (savedPlaceId: string): Promise<SavedPlace> => adaptSavedPlace(await client.request('/api/v1/passenger/saved-places/{savedPlaceId}', { pathParams: { savedPlaceId } })), create: async (body: unknown): Promise<SavedPlace> => adaptSavedPlace(await client.request('/api/v1/passenger/saved-places', { method: 'POST', body })), update: async (savedPlaceId: string, body: unknown): Promise<SavedPlace> => adaptSavedPlace(await client.request('/api/v1/passenger/saved-places/{savedPlaceId}', { method: 'PUT', pathParams: { savedPlaceId }, body })), delete: (savedPlaceId: string) => client.request('/api/v1/passenger/saved-places/{savedPlaceId}', { method: 'DELETE', pathParams: { savedPlaceId } }) });
export const trustedContactsApi = (client: ApiClient) => ({ list: async (): Promise<TrustedContact[]> => mapList(await client.request('/api/v1/passenger/trusted-contacts'), adaptTrustedContact), get: async (contactId: string): Promise<TrustedContact> => adaptTrustedContact(await client.request('/api/v1/passenger/trusted-contacts/{contactId}', { pathParams: { contactId } })), create: async (body: unknown): Promise<TrustedContact> => adaptTrustedContact(await client.request('/api/v1/passenger/trusted-contacts', { method: 'POST', body })), update: async (contactId: string, body: unknown): Promise<TrustedContact> => adaptTrustedContact(await client.request('/api/v1/passenger/trusted-contacts/{contactId}', { method: 'PUT', pathParams: { contactId }, body })), delete: (contactId: string) => client.request('/api/v1/passenger/trusted-contacts/{contactId}', { method: 'DELETE', pathParams: { contactId } }) });
export const rideSearchApi = (client: ApiClient) => ({ search: async (body: unknown): Promise<RideSearchResult[]> => mapList(await client.request('/api/v1/passenger/ride-searches', { method: 'POST', body }), adaptRideSearchResult), results: async (searchId: string): Promise<RideSearchResult[]> => mapList(await client.request('/api/v1/passenger/ride-searches/{searchId}/results', { pathParams: { searchId } }), adaptRideSearchResult), result: async (searchId: string, resultId: string): Promise<RideSearchResult> => adaptRideSearchResult(await client.request('/api/v1/passenger/ride-searches/{searchId}/results/{resultId}', { pathParams: { searchId, resultId } })) });
export const bookingsApi = (client: ApiClient) => ({ list: async (): Promise<Booking[]> => mapList(await client.request('/api/v1/passenger/bookings'), adaptBooking), create: async (body: unknown, idempotencyKey: string): Promise<Booking> => adaptBooking(await client.request('/api/v1/passenger/bookings', { method: 'POST', body, headers: { 'Idempotency-Key': idempotencyKey } })), get: async (bookingId: string): Promise<Booking> => adaptBooking(await client.request('/api/v1/passenger/bookings/{bookingId}', { pathParams: { bookingId } })), cancel: (bookingId: string, body?: unknown) => client.request('/api/v1/passenger/bookings/{bookingId}/cancel', { method: 'POST', pathParams: { bookingId }, body }), earlyDropOff: (bookingId: string, body?: unknown) => client.request('/api/v1/passenger/bookings/{bookingId}/early-drop-off', { method: 'POST', pathParams: { bookingId }, body }), rate: (bookingId: string, body: unknown) => client.request('/api/v1/passenger/bookings/{bookingId}/rating', { method: 'POST', pathParams: { bookingId }, body }), receipt: (bookingId: string) => client.request('/api/v1/passenger/bookings/{bookingId}/receipt', { pathParams: { bookingId } }), share: (bookingId: string, body?: unknown) => client.request('/api/v1/passenger/bookings/{bookingId}/share', { method: 'POST', pathParams: { bookingId }, body }), shareLink: (bookingId: string, body?: unknown) => client.request('/api/v1/passenger/bookings/{bookingId}/share-link', { method: 'POST', pathParams: { bookingId }, body }) });
export const paymentsApi = (client: ApiClient) => ({ methods: () => client.request('/api/v1/passenger/payment-methods'), createMethod: (body: unknown) => client.request('/api/v1/passenger/payment-methods', { method: 'POST', body }), deleteMethod: (paymentMethodId: string) => client.request('/api/v1/passenger/payment-methods/{paymentMethodId}', { method: 'DELETE', pathParams: { paymentMethodId } }), setDefaultMethod: (paymentMethodId: string) => client.request('/api/v1/passenger/payment-methods/{paymentMethodId}/default', { method: 'POST', pathParams: { paymentMethodId } }), createIntent: async (body: unknown): Promise<PaymentIntent> => adaptPaymentIntent(await client.request('/api/v1/passenger/payments/intents', { method: 'POST', body })) });
export const tripsApi = (client: ApiClient) => ({ current: () => client.request('/api/v1/passenger/trips/current'), history: () => client.request('/api/v1/passenger/trips/history'), liveState: (tripId: string) => client.request('/api/v1/passenger/trips/{tripId}/live-state', { pathParams: { tripId } }) });
export const notificationsApi = (client: ApiClient) => ({ list: () => client.request('/api/v1/passenger/notifications'), markRead: (notificationId: string) => client.request('/api/v1/passenger/notifications/{notificationId}/read', { method: 'POST', pathParams: { notificationId } }), preferences: () => client.request('/api/v1/passenger/notification-preferences'), updatePreferences: (body: unknown) => client.request('/api/v1/passenger/notification-preferences', { method: 'PUT', body }), registerPush: (body: unknown) => client.request('/api/v1/passenger/push-registrations', { method: 'POST', body }) });
export const supportApi = (client: ApiClient) => ({ listTickets: () => client.request('/api/v1/passenger/support/tickets'), createTicket: (body: unknown) => client.request('/api/v1/passenger/support/tickets', { method: 'POST', body }), getTicket: (ticketId: string) => client.request('/api/v1/passenger/support/tickets/{ticketId}', { pathParams: { ticketId } }), createMessage: (ticketId: string, body: unknown) => client.request('/api/v1/passenger/support/tickets/{ticketId}/messages', { method: 'POST', pathParams: { ticketId }, body }) });
export const safetyApi = (client: ApiClient) => ({ createSosEvent: (body: unknown) => client.request('/api/v1/passenger/sos-events', { method: 'POST', body }) });
